### PR TITLE
Add Nvidia USA support

### PR DESCRIPTION
**Pull request by mbrotos**
Add USA Nvidia store functionality

### CODE REVIEW

**Comment by L3XANDR0** [comment]
Shouldn't Nvidia USA have it's own bot? I'm making that assumption since the class name is 'NvidiaDe', which has the Germany abbreviation as a suffix.

**Comment by mbrotos** [comment]
> Shouldn't Nvidia USA have it's own bot? I'm making that assumption since the class name is 'NvidiaDe', which has the Germany abbreviation as a suffix.

It is a very generic class which may need a more generic name.

**Comment by mbrotos** [comment]
> Shouldn't Nvidia USA have it's own bot? I'm making that assumption since the class name is 'NvidiaDe', which has the Germany abbreviation as a suffix.

more generic naming scheme needed yes

**Comment by nehalist** [comment]
There needs to be a separate crawler for every shop. Additionally this PR does not compile since the removal of `getRetailerName` violates the `CrawlerInterface`.

Closing as I've added nvidia.com myself in 87aea1beb3043942b2aee8a364222cf98df430a4

**Pull request closed without merging**
